#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e
export OHMYZSH=$HOME/.oh-my-zsh
if [ ! -d "$OHMYZSH" ]; then
     git clone git://github.com/jmerkow/oh-my-zsh.git $OHMYZSH
else
    echo $OHMYZSH already exists.
fi